export default {
  ADD_WORD: "ADD_WORD",
  REMOVE_WORD: "REMOVE_WORD",
  CHANGE_WORD: "CHANGE_WORD",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  CHANGE_COMPLEXITY: "CHANGE_COMPLEXITY",
  SET_CONTEXT: "SET_CONTEXT" 
}